games = [{"date": "2018-01-20", "with colonies": 1, "with platinum": 1,
          "players": [{"name": "alex", "bid": -1, "score": 45, "turn": 1},
                      {"name": "mart", "bid": 7, "score": 57, "turn": 0},
                      {"name": "rutger", "bid": 10, "score": 55, "turn": 2}, ], "cards": [
        {"name": "militia", "buys": [{"player": "alex", "amount bought": 2}, {"player": "mart", "amount bought": 2}, ]},
        {"name": "throne room", "buys": [{"player": "rutger", "amount bought": 2}, ]},
        {"name": "city", "buys": [{"player": "alex", "amount bought": 1}, ]},
        {"name": "quarry", "buys": [{"player": "rutger", "amount bought": 1}, ]}, {"name": "monument", "buys": []},
        {"name": "village", "buys": []}, {"name": "contraband", "buys": [{"player": "mart", "amount bought": 1},
                                                                         {"player": "rutger", "amount bought": 1}, ]},
        {"name": "venture", "buys": []}, {"name": "artisan", "buys": [{"player": "rutger", "amount bought": 1}, ]},
        {"name": "market",
         "buys": [{"player": "alex", "amount bought": 2}, {"player": "rutger", "amount bought": 8}, ]}, ], "votes": []},
         {"date": "2018-01-20", "with colonies": 1, "with platinum": 1,
          "players": [{"name": "alex", "bid": 16, "score": 33, "turn": 0},
                      {"name": "mart", "bid": 16, "score": 29, "turn": 2},
                      {"name": "rutger", "bid": 23, "score": 59, "turn": 1}, ],
          "cards": [{"name": "peddler", "buys": [{"player": "alex", "amount bought": 2}, ]},
                    {"name": "counting house", "buys": []}, {"name": "royal seal",
                                                             "buys": [{"player": "alex", "amount bought": 3},
                                                                      {"player": "mart", "amount bought": 2},
                                                                      {"player": "rutger", "amount bought": 5}, ]},
                    {"name": "bank",
                     "buys": [{"player": "alex", "amount bought": 2}, {"player": "mart", "amount bought": 3},
                              {"player": "rutger", "amount bought": 1}, ]},
                    {"name": "forge", "buys": [{"player": "mart", "amount bought": 1}, ]},
                    {"name": "poacher", "buys": []}, {"name": "artisan", "buys": []}, {"name": "witch", "buys": [
                  {"player": "alex", "amount bought": 3}, {"player": "mart", "amount bought": 1}, ]},
                    {"name": "village", "buys": [{"player": "alex", "amount bought": 4}, ]}, {"name": "bureaucrat",
                                                                                              "buys": [
                                                                                                  {"player": "alex",
                                                                                                   "amount bought": 1},
                                                                                                  {"player": "mart",
                                                                                                   "amount bought": 1}, ]}, ],
          "votes": [{"card": "royal seal", "initiator": "mart",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "rutger", "vote": 0}, ]}, {"card": "witch", "initiator": "rutger",
                                                                     "votes": [{"player": "alex", "vote": 0},
                                                                               {"player": "mart", "vote": 0},
                                                                               {"player": "rutger", "vote": 1}, ]},
                    {"card": "bandit", "initiator": "rutger",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "rutger", "vote": 1}, ]}, {"card": "mine", "initiator": "alex",
                                                                     "votes": [{"player": "alex", "vote": 1},
                                                                               {"player": "mart", "vote": 1},
                                                                               {"player": "rutger", "vote": 1}, ]},
                    {"card": "gardens", "initiator": "mart",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "rutger", "vote": 1}, ]}, ]},
         {"date": "2018-01-20", "with colonies": 1, "with platinum": 1,
          "players": [{"name": "alex", "bid": 18, "score": 33, "turn": 1},
                      {"name": "mart", "bid": 9, "score": 34, "turn": 0},
                      {"name": "rutger", "bid": 10, "score": 50, "turn": 2}, ],
          "cards": [{"name": "counting house", "buys": []}, {"name": "worker's village", "buys": []}, {"name": "forge",
                                                                                                       "buys": [{
                                                                                                                    "player": "alex",
                                                                                                                    "amount bought": 1},
                                                                                                                {
                                                                                                                    "player": "mart",
                                                                                                                    "amount bought": 1},
                                                                                                                {
                                                                                                                    "player": "rutger",
                                                                                                                    "amount bought": 2}, ]},
                    {"name": "quarry", "buys": [{"player": "rutger", "amount bought": 1}, ]}, {"name": "mint", "buys": [
                  {"player": "alex", "amount bought": 1}, {"player": "rutger", "amount bought": 1}, ]},
                    {"name": "market", "buys": [{"player": "mart", "amount bought": 1}, ]},
                    {"name": "throne room", "buys": [{"player": "alex", "amount bought": 1}, ]},
                    {"name": "council room",
                     "buys": [{"player": "alex", "amount bought": 1}, {"player": "mart", "amount bought": 2}, ]},
                    {"name": "harbinger", "buys": []},
                    {"name": "cellar", "buys": [{"player": "alex", "amount bought": 1}, ]}, ], "votes": [
             {"card": "royal seal", "initiator": "alex",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                        {"player": "rutger", "vote": 1}, ]}, {"card": "forge", "initiator": "mart",
                                                              "votes": [{"player": "alex", "vote": 1},
                                                                        {"player": "mart", "vote": 1},
                                                                        {"player": "rutger", "vote": 0}, ]},
             {"card": "moat", "initiator": "rutger",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                        {"player": "rutger", "vote": 1}, ]}, ]},
         {"date": "2018-02-24", "with colonies": 1, "with platinum": 1,
          "players": [{"name": "alex", "bid": 13, "score": 24, "turn": 2},
                      {"name": "mart", "bid": 8, "score": 13, "turn": 1},
                      {"name": "martin", "bid": 5, "score": 9, "turn": 0},
                      {"name": "rutger", "bid": 13, "score": 9, "turn": 3}, ],
          "cards": [{"name": "council room", "buys": []}, {"name": "village", "buys": []}, {"name": "grand market",
                                                                                            "buys": [{"player": "alex",
                                                                                                      "amount bought": 1},
                                                                                                     {"player": "mart",
                                                                                                      "amount bought": 1},
                                                                                                     {
                                                                                                         "player": "rutger",
                                                                                                         "amount bought": 2}, ]},
                    {"name": "vault", "buys": [{"player": "rutger", "amount bought": 1}, ]}, {"name": "counting house",
                                                                                              "buys": [
                                                                                                  {"player": "alex",
                                                                                                   "amount bought": 1},
                                                                                                  {"player": "rutger",
                                                                                                   "amount bought": 1}, ]},
                    {"name": "contraband", "buys": [{"player": "mart", "amount bought": 1}, ]},
                    {"name": "poor house", "buys": [{"player": "alex", "amount bought": 1}, ]}, {"name": "pillage",
                                                                                                 "buys": [
                                                                                                     {"player": "alex",
                                                                                                      "amount bought": 1},
                                                                                                     {"player": "mart",
                                                                                                      "amount bought": 2}, ]},
                    {"name": "market square", "buys": []},
                    {"name": "squire", "buys": [{"player": "alex", "amount bought": 1}, ]}, ], "votes": [
             {"card": "mystic", "initiator": "alex",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1}, {"player": "martin", "vote": 1},
                        {"player": "rutger", "vote": 1}, ]}, {"card": "militia", "initiator": "rutger",
                                                              "votes": [{"player": "alex", "vote": 1},
                                                                        {"player": "mart", "vote": 1},
                                                                        {"player": "martin", "vote": 1},
                                                                        {"player": "rutger", "vote": 1}, ]},
             {"card": "marauder", "initiator": "martin",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1}, {"player": "martin", "vote": 1},
                        {"player": "rutger", "vote": 1}, ]}, {"card": "artisan", "initiator": "mart",
                                                              "votes": [{"player": "alex", "vote": 1},
                                                                        {"player": "mart", "vote": 1},
                                                                        {"player": "martin", "vote": 1},
                                                                        {"player": "rutger", "vote": 1}, ]}, ]},
         {"date": "2018-02-24", "with colonies": 1, "with platinum": 1,
          "players": [{"name": "alex", "bid": 0, "score": 5, "turn": 4},
                      {"name": "mart", "bid": 0, "score": 55, "turn": 3},
                      {"name": "martin", "bid": 0, "score": 37, "turn": 1},
                      {"name": "rutger", "bid": 0, "score": 69, "turn": 0},
                      {"name": "angela", "bid": 0, "score": 37, "turn": 2}, ],
          "cards": [{"name": "altar", "buys": [{"player": "alex", "amount bought": 1}, ]}, {"name": "storeroom",
                                                                                            "buys": [{"player": "alex",
                                                                                                      "amount bought": 1},
                                                                                                     {"player": "mart",
                                                                                                      "amount bought": 1},
                                                                                                     {
                                                                                                         "player": "martin",
                                                                                                         "amount bought": 1},
                                                                                                     {
                                                                                                         "player": "angela",
                                                                                                         "amount bought": 1}, ]},
                    {"name": "counterfeit", "buys": [{"player": "angela", "amount bought": 1}, ]},
                    {"name": "vagrant", "buys": [{"player": "martin", "amount bought": 1}, ]},
                    {"name": "trade route", "buys": [{"player": "angela", "amount bought": 2}, ]},
                    {"name": "royal seal",
                     "buys": [{"player": "alex", "amount bought": 1}, {"player": "mart", "amount bought": 3},
                              {"player": "martin", "amount bought": 2}, {"player": "rutger", "amount bought": 3}, ]},
                    {"name": "quarry", "buys": [{"player": "alex", "amount bought": 1}, ]}, {"name": "mine", "buys": [
                  {"player": "alex", "amount bought": 4}, {"player": "angela", "amount bought": 1}, ]},
                    {"name": "poacher", "buys": []}, {"name": "harbinger", "buys": []}, ], "votes": [
             {"card": "gardens", "initiator": "mart",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1}, {"player": "martin", "vote": 1},
                        {"player": "rutger", "vote": 1}, {"player": "angela", "vote": 1}, ]},
             {"card": "mystic", "initiator": "alex",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1}, {"player": "martin", "vote": 1},
                        {"player": "rutger", "vote": 1}, {"player": "angela", "vote": 1}, ]},
             {"card": "urchin", "initiator": "martin",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1}, {"player": "martin", "vote": 1},
                        {"player": "rutger", "vote": 1}, {"player": "angela", "vote": 1}, ]},
             {"card": "cultist", "initiator": "rutger",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1}, {"player": "martin", "vote": 1},
                        {"player": "rutger", "vote": 1}, {"player": "angela", "vote": 1}, ]}, ]},
         {"date": "2018-02-24", "with colonies": 1, "with platinum": 1,
          "players": [{"name": "alex", "bid": -5, "score": 37, "turn": 2},
                      {"name": "mart", "bid": -2, "score": 33, "turn": 1},
                      {"name": "martin", "bid": 9, "score": 29, "turn": 0},
                      {"name": "rutger", "bid": 3, "score": 43, "turn": 3}, ], "cards": [{"name": "mystic", "buys": []},
                                                                                         {"name": "vagrant", "buys": [
                                                                                             {"player": "martin",
                                                                                              "amount bought": 2},
                                                                                             {"player": "rutger",
                                                                                              "amount bought": 1}, ]},
                                                                                         {"name": "hoard", "buys": []},
                                                                                         {"name": "expand", "buys": []},
                                                                                         {"name": "bureaucrat",
                                                                                          "buys": [{"player": "martin",
                                                                                                    "amount bought": 2}, ]},
                                                                                         {"name": "merchant",
                                                                                          "buys": []},
                                                                                         {"name": "smithy", "buys": [
                                                                                             {"player": "alex",
                                                                                              "amount bought": 3},
                                                                                             {"player": "mart",
                                                                                              "amount bought": 4},
                                                                                             {"player": "martin",
                                                                                              "amount bought": 2},
                                                                                             {"player": "rutger",
                                                                                              "amount bought": 1}, ]},
                                                                                         {"name": "king's court",
                                                                                          "buys": [{"player": "mart",
                                                                                                    "amount bought": 2}, ]},
                                                                                         {"name": "peddler",
                                                                                          "buys": []},
                                                                                         {"name": "rebuild", "buys": [
                                                                                             {"player": "alex",
                                                                                              "amount bought": 2},
                                                                                             {"player": "mart",
                                                                                              "amount bought": 1},
                                                                                             {"player": "martin",
                                                                                              "amount bought": 2},
                                                                                             {"player": "rutger",
                                                                                              "amount bought": 2}, ]}, ],
          "votes": [{"card": "goons", "initiator": "alex",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "martin", "vote": 1}, {"player": "rutger", "vote": 1}, ]},
                    {"card": "bureaucrat", "initiator": "martin",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "martin", "vote": 1}, {"player": "rutger", "vote": 0}, ]},
                    {"card": "forge", "initiator": "rutger",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "martin", "vote": 1}, {"player": "rutger", "vote": 1}, ]},
                    {"card": "venture", "initiator": "mart",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "martin", "vote": 1}, {"player": "rutger", "vote": 1}, ]}, ]},
         {"date": "2018-02-24", "with colonies": 1, "with platinum": 1,
          "players": [{"name": "alex", "bid": 2, "score": 16, "turn": 3},
                      {"name": "mart", "bid": 6, "score": 33, "turn": 2},
                      {"name": "martin", "bid": 12, "score": 19, "turn": 1},
                      {"name": "rutger", "bid": 7, "score": 39, "turn": 0}, ], "cards": [{"name": "cellar", "buys": [
             {"player": "alex", "amount bought": 2}, {"player": "martin", "amount bought": 1},
             {"player": "rutger", "amount bought": 1}, ]}, {"name": "library",
                                                            "buys": [{"player": "alex", "amount bought": 1},
                                                                     {"player": "mart", "amount bought": 6},
                                                                     {"player": "martin", "amount bought": 1},
                                                                     {"player": "rutger", "amount bought": 2}, ]},
                                                                                         {"name": "moat", "buys": [
                                                                                             {"player": "alex",
                                                                                              "amount bought": 1},
                                                                                             {"player": "martin",
                                                                                              "amount bought": 1},
                                                                                             {"player": "rutger",
                                                                                              "amount bought": 1}, ]},
                                                                                         {"name": "laboratory",
                                                                                          "buys": [{"player": "martin",
                                                                                                    "amount bought": 3}, ]},
                                                                                         {"name": "expand", "buys": [
                                                                                             {"player": "martin",
                                                                                              "amount bought": 2}, ]},
                                                                                         {"name": "venture",
                                                                                          "buys": []},
                                                                                         {"name": "peddler", "buys": [
                                                                                             {"player": "martin",
                                                                                              "amount bought": 2}, ]},
                                                                                         {"name": "hunting grounds",
                                                                                          "buys": [{"player": "rutger",
                                                                                                    "amount bought": 1}, ]},
                                                                                         {"name": "death cart",
                                                                                          "buys": [{"player": "alex",
                                                                                                    "amount bought": 2},
                                                                                                   {"player": "mart",
                                                                                                    "amount bought": 3},
                                                                                                   {"player": "martin",
                                                                                                    "amount bought": 3},
                                                                                                   {"player": "rutger",
                                                                                                    "amount bought": 2}, ]},
                                                                                         {"name": "marauder", "buys": [
                                                                                             {"player": "alex",
                                                                                              "amount bought": 1},
                                                                                             {"player": "mart",
                                                                                              "amount bought": 2},
                                                                                             {"player": "martin",
                                                                                              "amount bought": 1}, ]}, ],
          "votes": [{"card": "beggar", "initiator": "alex",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "martin", "vote": 1}, {"player": "rutger", "vote": 1}, ]},
                    {"card": "bandit", "initiator": "rutger",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "martin", "vote": 1}, {"player": "rutger", "vote": 1}, ]},
                    {"card": "bureaucrat", "initiator": "martin",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "martin", "vote": 1}, {"player": "rutger", "vote": 1}, ]},
                    {"card": "merchant", "initiator": "mart",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "martin", "vote": 1}, {"player": "rutger", "vote": 1}, ]}, ]},
         {"date": "2018-02-24", "with colonies": 1, "with platinum": 1,
          "players": [{"name": "mart", "bid": 8, "score": 59, "turn": 1},
                      {"name": "martin", "bid": 8, "score": 33, "turn": 0},
                      {"name": "rutger", "bid": 8, "score": 43, "turn": 2}, ], "cards": [{"name": "market", "buys": []},
                                                                                         {"name": "cellar", "buys": [
                                                                                             {"player": "mart",
                                                                                              "amount bought": 1},
                                                                                             {"player": "martin",
                                                                                              "amount bought": 1},
                                                                                             {"player": "rutger",
                                                                                              "amount bought": 1}, ]},
                                                                                         {"name": "vassal", "buys": [
                                                                                             {"player": "mart",
                                                                                              "amount bought": 1},
                                                                                             {"player": "martin",
                                                                                              "amount bought": 1}, ]},
                                                                                         {"name": "peddler", "buys": [
                                                                                             {"player": "mart",
                                                                                              "amount bought": 4},
                                                                                             {"player": "martin",
                                                                                              "amount bought": 4}, ]},
                                                                                         {"name": "expand", "buys": []},
                                                                                         {"name": "fortress", "buys": [
                                                                                             {"player": "martin",
                                                                                              "amount bought": 1}, ]},
                                                                                         {"name": "hunting grounds",
                                                                                          "buys": [{"player": "mart",
                                                                                                    "amount bought": 2},
                                                                                                   {"player": "martin",
                                                                                                    "amount bought": 1},
                                                                                                   {"player": "rutger",
                                                                                                    "amount bought": 2}, ]},
                                                                                         {"name": "wandering minstrel",
                                                                                          "buys": [{"player": "mart",
                                                                                                    "amount bought": 1},
                                                                                                   {"player": "martin",
                                                                                                    "amount bought": 1}, ]},
                                                                                         {"name": "bandit camp",
                                                                                          "buys": [{"player": "mart",
                                                                                                    "amount bought": 1},
                                                                                                   {"player": "martin",
                                                                                                    "amount bought": 3},
                                                                                                   {"player": "rutger",
                                                                                                    "amount bought": 2}, ]},
                                                                                         {"name": "bank",
                                                                                          "buys": []}, ], "votes": [
             {"card": "artisan", "initiator": "mart",
              "votes": [{"player": "mart", "vote": 1}, {"player": "martin", "vote": 1},
                        {"player": "rutger", "vote": 1}, ]}, {"card": "witch", "initiator": "rutger",
                                                              "votes": [{"player": "mart", "vote": 1},
                                                                        {"player": "martin", "vote": 1},
                                                                        {"player": "rutger", "vote": 1}, ]},
             {"card": "bureaucrat", "initiator": "martin",
              "votes": [{"player": "mart", "vote": 1}, {"player": "martin", "vote": 1},
                        {"player": "rutger", "vote": 1}, ]}, ]},
         {"date": "2018-02-24", "with colonies": 1, "with platinum": 1,
          "players": [{"name": "alex", "bid": 3, "score": 45, "turn": 0},
                      {"name": "mart", "bid": -5, "score": 67, "turn": 2},
                      {"name": "rutger", "bid": 3, "score": 55, "turn": 1}, ],
          "cards": [{"name": "monument", "buys": []}, {"name": "venture",
                                                       "buys": [{"player": "alex", "amount bought": 1},
                                                                {"player": "rutger", "amount bought": 1}, ]},
                    {"name": "loan", "buys": []},
                    {"name": "masquerade", "buys": [{"player": "mart", "amount bought": 3}, ]}, {"name": "mill",
                                                                                                 "buys": [
                                                                                                     {"player": "mart",
                                                                                                      "amount bought": 1},
                                                                                                     {
                                                                                                         "player": "rutger",
                                                                                                         "amount bought": 1}, ]},
                    {"name": "secret passage", "buys": []}, {"name": "death cart",
                                                             "buys": [{"player": "alex", "amount bought": 2},
                                                                      {"player": "mart", "amount bought": 2},
                                                                      {"player": "rutger", "amount bought": 2}, ]},
                    {"name": "procession", "buys": []}, {"name": "rogue",
                                                         "buys": [{"player": "alex", "amount bought": 2},
                                                                  {"player": "mart", "amount bought": 2},
                                                                  {"player": "rutger", "amount bought": 2}, ]},
                    {"name": "sage", "buys": [{"player": "alex", "amount bought": 1}, ]}, ], "votes": []},
         {"date": "2018-03-24", "with colonies": 1, "with platinum": 0,
          "players": [{"name": "alex", "bid": 6, "score": 62, "turn": 1},
                      {"name": "mart", "bid": 6, "score": 88, "turn": 4},
                      {"name": "rutger", "bid": 15, "score": 99, "turn": 2}, ],
          "cards": [{"name": "bandit camp", "buys": [{"player": "rutger", "amount bought": 1}, ]},
                    {"name": "mining village", "buys": []}, {"name": "duke",
                                                             "buys": [{"player": "mart", "amount bought": 6},
                                                                      {"player": "rutger", "amount bought": 6}, ]},
                    {"name": "ironworks", "buys": []},
                    {"name": "nobles", "buys": [{"player": "rutger", "amount bought": 2}, ]}, {"name": "pillage",
                                                                                               "buys": [
                                                                                                   {"player": "alex",
                                                                                                    "amount bought": 1},
                                                                                                   {"player": "mart",
                                                                                                    "amount bought": 2},
                                                                                                   {"player": "rutger",
                                                                                                    "amount bought": 1}, ]},
                    {"name": "death cart", "buys": [{"player": "alex", "amount bought": 3}, ]}, {"name": "throne room",
                                                                                                 "buys": [
                                                                                                     {"player": "alex",
                                                                                                      "amount bought": 2},
                                                                                                     {"player": "mart",
                                                                                                      "amount bought": 2}, ]},
                    {"name": "graverobber", "buys": [{"player": "mart", "amount bought": 1}, ]},
                    {"name": "festival", "buys": [{"player": "mart", "amount bought": 2}, ]}, ], "votes": [
             {"card": "poor house", "initiator": "alex",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                        {"player": "rutger", "vote": 1}, ]}, {"card": "urchin", "initiator": "",
                                                              "votes": [{"player": "alex", "vote": 1},
                                                                        {"player": "mart", "vote": 1},
                                                                        {"player": "rutger", "vote": 1}, ]},
             {"card": "rogue", "initiator": "rutger",
              "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                        {"player": "rutger", "vote": 1}, ]}, ]},
         {"date": "2018-06-17", "with colonies": 1, "with platinum": 0,
          "players": [{"name": "alex", "bid": 10, "score": 56, "turn": 2},
                      {"name": "mart", "bid": 5, "score": 64, "turn": 3},
                      {"name": "rutger", "bid": 9, "score": 73, "turn": 1}, ], "cards": [{"name": "council room",
                                                                                          "buys": [{"player": "alex",
                                                                                                    "amount bought": 2},
                                                                                                   {"player": "mart",
                                                                                                    "amount bought": 2}, ]},
                                                                                         {"name": "counterfeit",
                                                                                          "buys": []},
                                                                                         {"name": "wandering minstrel",
                                                                                          "buys": [{"player": "alex",
                                                                                                    "amount bought": 3},
                                                                                                   {"player": "mart",
                                                                                                    "amount bought": 2},
                                                                                                   {"player": "rutger",
                                                                                                    "amount bought": 2}, ]},
                                                                                         {"name": "festival", "buys": [
                                                                                             {"player": "alex",
                                                                                              "amount bought": 1},
                                                                                             {"player": "mart",
                                                                                              "amount bought": 1},
                                                                                             {"player": "rutger",
                                                                                              "amount bought": 1}, ]},
                                                                                         {"name": "mine", "buys": []},
                                                                                         {"name": "village", "buys": [
                                                                                             {"player": "alex",
                                                                                              "amount bought": 1}, ]},
                                                                                         {"name": "gardens",
                                                                                          "buys": []},
                                                                                         {"name": "scavenger", "buys": [
                                                                                             {"player": "alex",
                                                                                              "amount bought": 1}, ]},
                                                                                         {"name": "bandit camp",
                                                                                          "buys": [{"player": "alex",
                                                                                                    "amount bought": 2},
                                                                                                   {"player": "mart",
                                                                                                    "amount bought": 1},
                                                                                                   {"player": "rutger",
                                                                                                    "amount bought": 3}, ]},
                                                                                         {"name": "poor house",
                                                                                          "buys": [{"player": "alex",
                                                                                                    "amount bought": 1},
                                                                                                   {"player": "rutger",
                                                                                                    "amount bought": 2}, ]}, ],
          "votes": [{"card": "urchin", "initiator": "rutger",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "rutger", "vote": 1}, ]}, {"card": "rogue", "initiator": "mart",
                                                                     "votes": [{"player": "alex", "vote": 1},
                                                                               {"player": "mart", "vote": 1},
                                                                               {"player": "rutger", "vote": 1}, ]},
                    {"card": "marauder", "initiator": "alex",
                     "votes": [{"player": "alex", "vote": 1}, {"player": "mart", "vote": 1},
                               {"player": "rutger", "vote": 1}, ]}, ]}, ]
