kingdomcards = [

    # --- BASE --- #

    {
        "name": "artisan",
        "expansion": "base",
        "cost": 6,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "bandit",
        "expansion": "base",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "bureaucrat",
        "expansion": "base",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "cellar",
        "expansion": "base",
        "cost": 2,
        "draw": 0,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "chapel",
        "expansion": "base",
        "cost": 2,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "council room",
        "expansion": "base",
        "cost": 5,
        "draw": 4,
        "actions": 0,
        "coins": 0,
        "buys": 1,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "festival",
        "expansion": "base",
        "cost": 5,
        "draw": 0,
        "actions": 2,
        "coins": 2,
        "buys": 1,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "gardens",
        "expansion": "base",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["victory"]
    },
    {
        "name": "harbinger",
        "expansion": "base",
        "cost": 3,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "laboratory",
        "expansion": "base",
        "cost": 5,
        "draw": 2,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "library",
        "expansion": "base",
        "cost": 5,
        "draw": 4,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "market",
        "expansion": "base",
        "cost": 5,
        "draw": 1,
        "actions": 1,
        "coins": 1,
        "buys": 1,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "merchant",
        "expansion": "base",
        "cost": 3,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "militia",
        "expansion": "base",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "mine",
        "expansion": "base",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "moat",
        "expansion": "base",
        "cost": 2,
        "draw": 2,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "reaction"]
    },
    {
        "name": "poacher",
        "expansion": "base",
        "cost": 4,
        "draw": 1,
        "actions": 1,
        "coins": 1,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "remodel",
        "expansion": "base",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "smithy",
        "expansion": "base",
        "cost": 4,
        "draw": 3,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "throne room",
        "expansion": "base",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "vassal",
        "expansion": "base",
        "cost": 3,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "village",
        "expansion": "base",
        "cost": 3,
        "draw": 1,
        "actions": 2,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "witch",
        "expansion": "base",
        "cost": 5,
        "draw": 2,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },

    # --- INTRIGUE --- #

    {
        "name": "baron",
        "expansion": "intrigue",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 1,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "bridge",
        "expansion": "intrigue",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 1,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "conspirator",
        "expansion": "intrigue",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "courtier",
        "expansion": "intrigue",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "diplomat",
        "expansion": "intrigue",
        "cost": 4,
        "draw": 2,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "reaction"]
    },
    {
        "name": "duke",
        "expansion": "intrigue",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["victory"]
    },
    {
        "name": "courtyard",
        "expansion": "intrigue",
        "cost": 2,
        "draw": 3,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "harem",
        "expansion": "intrigue",
        "cost": 6,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["treasure", "victory"]
    },
    {
        "name": "ironworks",
        "expansion": "intrigue",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "lurker",
        "expansion": "intrigue",
        "cost": 2,
        "draw": 0,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "masquerade",
        "expansion": "intrigue",
        "cost": 3,
        "draw": 2,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "mill",
        "expansion": "intrigue",
        "cost": 4,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "victory"]
    },
    {
        "name": "mining village",
        "expansion": "intrigue",
        "cost": 4,
        "draw": 1,
        "actions": 2,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "minion",
        "expansion": "intrigue",
        "cost": 5,
        "draw": 0,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "nobles",
        "expansion": "intrigue",
        "cost": 6,
        "draw": 3,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "victory"]
    },
    {
        "name": "patrol",
        "expansion": "intrigue",
        "cost": 5,
        "draw": 3,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "pawn",
        "expansion": "intrigue",
        "cost": 2,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "replace",
        "expansion": "intrigue",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "secret passage",
        "expansion": "intrigue",
        "cost": 4,
        "draw": 2,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "shanty town",
        "expansion": "intrigue",
        "cost": 3,
        "draw": 0,
        "actions": 2,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "steward",
        "expansion": "intrigue",
        "cost": 3,
        "draw": 2,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "swindler",
        "expansion": "intrigue",
        "cost": 3,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "torturer",
        "expansion": "intrigue",
        "cost": 5,
        "draw": 3,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "trading post",
        "expansion": "intrigue",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "upgrade",
        "expansion": "intrigue",
        "cost": 5,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "wishing well",
        "expansion": "intrigue",
        "cost": 3,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },

    # --- DARK AGES --- #

    {
        "name": "altar",
        "expansion": "dark ages",
        "cost": 6,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "bandit camp",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 1,
        "actions": 2,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "beggar",
        "expansion": "dark ages",
        "cost": 2,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "reaction"]
    },
    {
        "name": "count",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 3,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "counterfeit",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 1,
        "buys": 1,
        "trasher": 1,
        "types": ["treasure"]
    },
    {
        "name": "cultist",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 2,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack", "looter"]
    },
    {
        "name": "death cart",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 5,
        "buys": 0,
        "trasher": 1,
        "types": ["action", "looter"]
    },
    {
        "name": "feodum",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["victory"]
    },
    {
        "name": "forager",
        "expansion": "dark ages",
        "cost": 3,
        "draw": 0,
        "actions": 1,
        "coins": 0,
        "buys": 1,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "fortress",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 1,
        "actions": 2,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "graverobber",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "hermit",
        "expansion": "dark ages",
        "cost": 3,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "hunting grounds",
        "expansion": "dark ages",
        "cost": 6,
        "draw": 4,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "ironmonger",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "junk dealer",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 1,
        "actions": 1,
        "coins": 1,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "knights",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack", "knight"]
    },
    {
        "name": "marauder",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "market square",
        "expansion": "dark ages",
        "cost": 3,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 1,
        "trasher": 0,
        "types": ["action", "reaction"]
    },
    {
        "name": "mystic",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 0,
        "actions": 1,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "pillage",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "poor house",
        "expansion": "dark ages",
        "cost": 1,
        "draw": 0,
        "actions": 0,
        "coins": 4,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "procession",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "rats",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "rebuild",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 0,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "rogue",
        "expansion": "dark ages",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "sage",
        "expansion": "dark ages",
        "cost": 3,
        "draw": 0,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "scavenger",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "squire",
        "expansion": "dark ages",
        "cost": 2,
        "draw": 0,
        "actions": 0,
        "coins": 1,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "storeroom",
        "expansion": "dark ages",
        "cost": 3,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 1,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "urchin",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "vagrant",
        "expansion": "dark ages",
        "cost": 2,
        "draw": 1,
        "actions": 1,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "wandering minstrel",
        "expansion": "dark ages",
        "cost": 4,
        "draw": 1,
        "actions": 2,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },

    # --- PROSPERITY --- #

    {
        "name": "bank",
        "expansion": "prosperity",
        "cost": 7,
        "draw": 0,
        "actions": 0,
        "coins": 1,
        "buys": 0,
        "trasher": 0,
        "types": ["treasure"]
    },
    {
        "name": "bishop",
        "expansion": "prosperity",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 1,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "city",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 1,
        "actions": 2,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "contraband",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 3,
        "actions": 0,
        "coins": 0,
        "buys": 1,
        "trasher": 0,
        "types": ["treasure"]
    },
    {
        "name": "counting house",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "expand",
        "expansion": "prosperity",
        "cost": 7,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "forge",
        "expansion": "prosperity",
        "cost": 7,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "goons",
        "expansion": "prosperity",
        "cost": 6,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 1,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "grand market",
        "expansion": "prosperity",
        "cost": 6,
        "draw": 1,
        "actions": 1,
        "coins": 2,
        "buys": 1,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "hoard",
        "expansion": "prosperity",
        "cost": 6,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["treasure"]
    },
    {
        "name": "king's court",
        "expansion": "prosperity",
        "cost": 7,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "loan",
        "expansion": "prosperity",
        "cost": 3,
        "draw": 0,
        "actions": 0,
        "coins": 1,
        "buys": 0,
        "trasher": 0,
        "types": ["treasure"]
    },
    {
        "name": "mint",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "monument",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "mountebank",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "peddler",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 1,
        "actions": 1,
        "coins": 1,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "quarry",
        "expansion": "prosperity",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 1,
        "buys": 0,
        "trasher": 0,
        "types": ["treasure"]
    },
    {
        "name": "rabble",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 3,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "attack"]
    },
    {
        "name": "royal seal",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 2,
        "buys": 0,
        "trasher": 0,
        "types": ["treasure"]
    },
    {
        "name": "talisman",
        "expansion": "prosperity",
        "cost": 4,
        "draw": 0,
        "actions": 0,
        "coins": 1,
        "buys": 0,
        "trasher": 0,
        "types": ["treasure"]
    },
    {
        "name": "trade route",
        "expansion": "prosperity",
        "cost": 3,
        "draw": 0,
        "actions": 0,
        "coins": 0,
        "buys": 1,
        "trasher": 1,
        "types": ["action"]
    },
    {
        "name": "vault",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 2,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action"]
    },
    {
        "name": "venture",
        "expansion": "prosperity",
        "cost": 5,
        "draw": 0,
        "actions": 0,
        "coins": 1,
        "buys": 0,
        "trasher": 0,
        "types": ["treasure"]
    },
    {
        "name": "watchtower",
        "expansion": "prosperity",
        "cost": 3,
        "draw": 2,
        "actions": 0,
        "coins": 0,
        "buys": 0,
        "trasher": 0,
        "types": ["action", "reaction"]
    },
    {
        "name": "worker's village",
        "expansion": "prosperity",
        "cost": 4,
        "draw": 1,
        "actions": 2,
        "coins": 0,
        "buys": 1,
        "trasher": 0,
        "types": ["action"]
    },
]
